### ISSUE TITLE
我这里测试好像不支持最新版的6.3.19

### ISSUE THREAD

**Issue by xuanyuan1hao** [ggwhsd/CTP-CSharp#1]
我这里测试好像不支持最新版的6.3.19

**Comment by fangjunai** [comment]
win10 64位，.net 6.0  , vs2022 环境报错。

System.TypeInitializationException
  HResult=0x80131534
  Message=The type initializer for 'CTPWrapper.ctpthostmdapiPINVOKE' threw an exception.
  Source=<无法计算异常源>
  StackTrace:
<无法计算异常堆栈跟踪>

  此异常最初是在此调用堆栈中引发的: 
    [外部代码]

内部异常 1:
TypeInitializationException: The type initializer for 'SWIGExceptionHelper' threw an exception.

内部异常 2:
BadImageFormatException: 试图加载格式不正确的程序。 (0x8007000B)

**Comment by fangjunai** [comment]
win10 64位，.net 6.0  , vs2022 环境报错。

System.TypeInitializationException
  HResult=0x80131534
  Message=The type initializer for 'CTPWrapper.ctpthostmdapiPINVOKE' threw an exception.
  Source=<无法计算异常源>
  StackTrace:
<无法计算异常堆栈跟踪>

  此异常最初是在此调用堆栈中引发的: 
    [外部代码]

内部异常 1:
TypeInitializationException: The type initializer for 'SWIGExceptionHelper' threw an exception.

内部异常 2:
BadImageFormatException: 试图加载格式不正确的程序。 (0x8007000B)

**Comment by ggwhsd** [comment]
Release里面的dll 暂时支持到.net framework，还没在.net core运行过，后续重新做个.net core的版本

**Comment by ggwhsd** [comment]
> 我这里测试好像不支持最新版的6.3.19

目前Release目录中的版本用的是6.5.1的CTP api制作的，只向后支持大于这个版本的

**Comment by ggwhsd** [comment]
> win10 64位，.net 6.0 , vs2022 环境报错。
> 
> System.TypeInitializationException HResult=0x80131534 Message=The type initializer for 'CTPWrapper.ctpthostmdapiPINVOKE' threw an exception. Source=<无法计算异常源> StackTrace: <无法计算异常堆栈跟踪>
> 
> 此异常最初是在此调用堆栈中引发的: [外部代码]
> 
> 内部异常 1: TypeInitializationException: The type initializer for 'SWIGExceptionHelper' threw an exception.
> 
> 内部异常 2: BadImageFormatException: 试图加载格式不正确的程序。 (0x8007000B)


我今天测试了下，报这个错，是因为CTPWrapper原先是.netframework下制作的，默认支持32位，.netcore默认是anycpu，支持64位，我建议是把应用程序改成x86平台运行，应该就可以解决这个报错。 最新的Release目录下也有net5下编译的CTP包(支持x86平台的CTP api)，可以试试。
