### ISSUE TITLE
CThostFtdcMdApi.SubscribeMarketData 参数类型对不上

### ISSUE THREAD

**Issue by dongdc21450** [ggwhsd/CTP-CSharp#2]
在CTP-CSharp-master\CTPWrapperForCSharp\CSharpLibraryCS\CThostFtdcMdApi.cs文件里,ppInstrumentID 参数类型是SWIGTYPE_p_p_char, 可是反编译看到CTPWrapper.dll里响应的参数是 string[]
![image](https://user-images.githubusercontent.com/27759317/167575783-78b48193-35fc-451e-97d1-9a5f1ab16aae.png)
![image](https://user-images.githubusercontent.com/27759317/167575870-bc2a0e0d-094e-40c6-95ec-651a01d8fa22.png)

**Comment by ggwhsd** [comment]
制作过程已经更新了swig用的配置文件，最终生成的是没有命名空间的c#代码。 也可以跳过制作dll的过程，直接参考Example里面的例子用。

**Comment by kuangxj** [comment]
这应该是C++的 std::string 转C# string unicode出现的swig_p_p_char 映射问题。
