### ISSUE TITLE
运行报错了

### ISSUE THREAD

**Issue by 394988736** [ggwhsd/CTP-CSharp#3]
![image](https://github.com/ggwhsd/CTP-CSharp/assets/81234257/6245d805-665a-4dfa-af43-6f03c1f4a7aa)
System.AccessViolationException:“尝试读取或写入受保护的内存。这通常指示其他内存已损坏。”

**Comment by ggwhsd** [comment]
这个是缺少对应的ctp的动态库文件（dll文件），需要放到程序运行目录中。

**Comment by hkdavechan** [comment]
![image](https://github.com/user-attachments/assets/afa1c34f-9940-430d-bc7f-673ac0d30835)
![image](https://github.com/user-attachments/assets/eb723230-e99a-477e-afb8-08ab1327a68b)
已經放好了DLL file 但仍出現問題
